language: r
r:
  - oldrel
  - release
  - devel

cache: packages

warnings_are_errors: false

after_success:
  - |
    if [[ $TRAVIS_R_VERSION == 3.3.* ]]; then
      Rscript -e 'install.packages("covr"); covr::codecov()';
    fi
